name: Newtwork Debugging in PowerVS

on:
  workflow_dispatch:

jobs:
  Wget:
    name: Wget - ${{ matrix.os }} (${{ matrix.architecture }}) [${{ matrix.runner-owner }}]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            architecture: x64
            runner-owner: "github-hosted"
          - os: ubuntu-22.04-ppc64le
            architecture: ppc64le
            runner-owner: "actions-runner-ppc64le"
					- os: ubuntu-22.04-powervs-selfhosted
            architecture: ppc64le
            runner-owner: "actions-runner-ppc64le"
    steps:
      - uses: actions/checkout@v4
      - name: Install strace
        run: |
          sudo apt install strace -y || sudo yum install strace -y
      - name: Download not reachable packages
        run: | 
					urls=(
					    "https://registry.npmjs.org/set-blocking/-/set-blocking-2.0.0.tgz"
					    "https://registry.npmjs.org/require-main-filename/-/require-main-filename-2.0.0.tgz"
					    "https://registry.npmjs.org/p-try/-/p-try-2.2.0.tgz"
					    "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz"
					    "https://registry.npmjs.org/is-plain-obj/-/is-plain-obj-2.1.0.tgz"
					    "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz"
					)
					
					# Output directory for downloaded files
					output_dir="./downloads"
					mkdir -p "$output_dir"
					
					# Download each file with `wget` and `strace`
					for url in "${urls[@]}"; do
					    file_name=$(basename "$url")
					    strace -e trace=network,open,read,write wget -d --tries=2 -O "${output_dir}/${file_name}" "$url"
					done
